"""
System Controller Module for Nova
Provides OS-level file and application control capabilities
"""

from .folder_manager import create_folder, delete_folder, get_desktop_path
from .file_manager import (
    open_file,
    get_file_info,
    list_files,
    search_files,
    get_directory_stats,
    get_largest_files,
    find_duplicate_files,
    create_text_file,
    copy_file,
    move_file,
    rename_file,
    safe_delete_file,
    inspect_zip_archive,
    extract_zip_archive,
    extract_text_content
)
from .app_launcher import launch_application
from .action_executor import execute_action, SystemActionExecutor, get_action_history, clear_action_log
from .system_controller import (
    get_battery_status,
    get_disk_space,
    get_top_processes,
    get_brightness,
    set_brightness,
    adjust_brightness,
    minimize_all_windows,
    get_clipboard_text,
    set_clipboard_text,
    transform_clipboard,
    get_cpu_metrics,
    get_ram_metrics,
    get_all_disks,
    terminate_process,
    get_display_info,
    get_system_info,
    volume_mute_toggle,
    volume_up,
    volume_down,
    # Universal Device Control — Extended Capabilities
    get_toggle_key_states,
    toggle_key,
    set_key,
    get_wifi_status,
    list_wifi_networks,
    set_wifi_state,
    get_bluetooth_status,
    get_network_adapters,
    get_hardware_info,
    get_active_power_plan,
    list_power_plans,
    get_mouse_info,
    list_all_processes,
    get_uptime,
    get_network_speed,
)
from .desktop_organizer import organize_directory, scan_unorganized_files

__all__ = [
    'create_folder',
    'delete_folder', 
    'get_desktop_path',
    'open_file',
    'get_file_info',
    'list_files',
    'search_files',
    'get_directory_stats',
    'get_largest_files',
    'find_duplicate_files',
    'create_text_file',
    'copy_file',
    'move_file',
    'rename_file',
    'safe_delete_file',
    'inspect_zip_archive',
    'extract_zip_archive',
    'extract_text_content',
    'launch_application',
    'execute_action',
    'SystemActionExecutor',
    'get_action_history',
    'clear_action_log',
    'get_battery_status',
    'get_disk_space',
    'get_top_processes',
    'get_brightness',
    'set_brightness',
    'adjust_brightness',
    'minimize_all_windows',
    'get_clipboard_text',
    'set_clipboard_text',
    'transform_clipboard',
    'get_cpu_metrics',
    'get_ram_metrics',
    'get_all_disks',
    'terminate_process',
    'get_display_info',
    'get_system_info',
    'volume_mute_toggle',
    'volume_up',
    'volume_down',
    'get_toggle_key_states',
    'toggle_key',
    'set_key',
    'get_wifi_status',
    'list_wifi_networks',
    'set_wifi_state',
    'get_bluetooth_status',
    'get_network_adapters',
    'get_hardware_info',
    'get_active_power_plan',
    'list_power_plans',
    'get_mouse_info',
    'list_all_processes',
    'get_uptime',
    'get_network_speed',
    'organize_directory',
    'scan_unorganized_files'
]

