"""
Proactive Interaction Module
Handles idle conversation and activity suggestions with random timing.

TTS routing
-----------
All speech goes through the TTS coordinator (PROACTIVE priority tier),
so proactive messages yield to user commands and reminders in the queue.
The coordinator import is lazy (inside _trigger_proactive_interaction)
to avoid a circular-import / initialization-order problem: this module
is imported early in the startup chain, before initialize_tts_coordinator()
has run.  Keeping the import lazy means the coordinator is only resolved
at the moment speech is actually needed, by which time initialization
is guaranteed to be complete.
"""

import time
import threading
import random

from instance.config import settings as CONFIG


def _speak_proactive(text: str) -> None:
    """Speak via the coordinator at PROACTIVE priority (lowest tier).

    Falls back to legacy.tts.speak() if the coordinator is unavailable.
    Import is intentionally lazy — see module docstring.
    """
    try:
        from extensions.system.tts_coordinator import speak as _coord_speak, TTSPriority
        _coord_speak(text, priority=TTSPriority.PROACTIVE)
    except Exception:
        try:
            from legacy.tts import speak as _direct_speak
            _direct_speak(text)
        except Exception:
            print(f"[PROACTIVE TTS] {text}")


class ProactiveInteraction:
    def __init__(self):
        self.last_interaction_time = time.time()
        self.idle_interval = self._get_random_interval()
        self.is_running = False
        self.thread = None
        self.do_not_disturb = False

    def _get_random_interval(self) -> int:
        """Return a random interval between 20 and 30 minutes (in seconds)."""
        return random.randint(20 * 60, 30 * 60)

    def reset_timer(self) -> None:
        """Reset idle timer on user interaction."""
        self.last_interaction_time = time.time()
        self.idle_interval = self._get_random_interval()

    def start(self) -> None:
        """Start proactive interaction monitoring."""
        if self.is_running:
            return
        self.is_running = True
        self.thread = threading.Thread(
            target=self._monitor_idle, daemon=True, name="assistant-proactive"
        )
        self.thread.start()

    def stop(self) -> None:
        """Stop proactive interaction monitoring."""
        self.is_running = False

    def _is_user_busy(self) -> bool:
        """Return True when the user should not be interrupted."""
        return self.do_not_disturb

    def _monitor_idle(self) -> None:
        """Monitor idle time and trigger proactive interaction when appropriate."""
        while self.is_running:
            try:
                time.sleep(60)  # check once per minute

                idle_time = time.time() - self.last_interaction_time

                if idle_time >= self.idle_interval and not self._is_user_busy():
                    self._trigger_proactive_interaction()
                    self.reset_timer()

            except Exception as exc:
                print(f"[Proactive Interaction Error] {exc}")

    def _trigger_proactive_interaction(self) -> None:
        """Trigger a proactive interaction via the RAG/assistant pipeline."""
        from datetime import datetime
        current_hour = datetime.now().hour

        if 18 <= current_hour <= 22:
            trigger = "@proactive: tomorrow_schedule"
        else:
            trigger = random.choice([
                "@proactive: light_conversation",
                "@proactive: suggest_activity",
            ])

        print(f"[PROACTIVE] Triggering pipeline with: {trigger}")

        try:
            # process_input() routes through the assistant, which calls the
            # TTS coordinator internally (COMMAND priority).  We do not call
            # _speak_proactive() here because the response is generated by the
            # assistant; just delegate.
            from legacy.assistant import process_input
            process_input(trigger)
        except Exception as exc:
            print(f"[PROACTIVE ERROR] Pipeline delegation failed: {exc}")


# ── Module-level singleton ────────────────────────────────────────────────────

_proactive_interaction: "ProactiveInteraction | None" = None


def get_proactive_interaction() -> ProactiveInteraction:
    """Get or create the global ProactiveInteraction instance."""
    global _proactive_interaction
    if _proactive_interaction is None:
        _proactive_interaction = ProactiveInteraction()
    return _proactive_interaction


def start_proactive_interaction() -> None:
    """Start proactive interaction monitoring."""
    get_proactive_interaction().start()


def reset_proactive_timer() -> None:
    """Reset the proactive interaction idle timer."""
    get_proactive_interaction().reset_timer()


def stop_proactive_interaction() -> None:
    """Stop proactive interaction monitoring."""
    get_proactive_interaction().stop()
