"""
Word (.docx) Document Generator for Nova Smart Assistant.
Generates professionally styled Word documents with titles, headings, bullet lists, and tables.
"""

import os
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def get_default_output_dir() -> str:
    """
    Get safe user Documents directory or fall back to Desktop.
    """
    home = os.path.expanduser("~")
    docs = os.path.join(home, "Documents")
    if os.path.exists(docs):
        return docs
    desktop = os.path.join(home, "Desktop")
    if os.path.exists(desktop):
        return desktop
    return home


def create_docx_document(
    title: str,
    content: str or List[Dict[str, Any]],
    filename: Optional[str] = None,
    author: Optional[str] = "Nova Assistant",
    category: Optional[str] = None,
    include_cover_page: bool = False
) -> Dict[str, Any]:
    """
    Create a styled .docx document.
    
    Args:
        title: Main document title
        content: String text or structured list of blocks:
                 [{"type": "heading", "level": 1, "text": "..."},
                  {"type": "paragraph", "text": "..."},
                  {"type": "quote", "text": "...", "author": "..."},
                  {"type": "bullet", "items": ["...", "..."]},
                  {"type": "number", "items": ["...", "..."]},
                  {"type": "page_break"},
                  {"type": "table", "headers": [...], "rows": [[...], [...]]}]
        filename: Target filename (.docx)
        author: Document metadata author
        category: Document category or topic
        include_cover_page: If True, adds a professional standalone cover page
    """
    try:
        import docx
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        doc = docx.Document()
        
        # Set core properties
        core_props = doc.core_properties
        core_props.title = title
        core_props.author = author
        core_props.created = datetime.now()
        if category:
            core_props.category = category

        # Add running header and footer to document sections
        section = doc.sections[0]
        header = section.header
        header_p = header.paragraphs[0]
        header_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        h_run = header_p.add_run(title)
        h_run.font.size = Pt(8.5)
        h_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        footer = section.footer
        footer_p = footer.paragraphs[0]
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        f_run = footer_p.add_run(f"Confidential & Proprietary • Generated by {author}")
        f_run.font.size = Pt(8.5)
        f_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        if include_cover_page:
            # Standalone Cover Page
            spacer_top = doc.add_paragraph()
            spacer_top.paragraph_format.space_before = Pt(140)

            c_title = doc.add_paragraph()
            c_title.alignment = WD_ALIGN_PARAGRAPH.LEFT
            c_run = c_title.add_run(title)
            c_run.font.size = Pt(32)
            c_run.font.bold = True
            c_run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

            if category:
                cat_p = doc.add_paragraph()
                cat_run = cat_p.add_run(category.upper())
                cat_run.font.size = Pt(11)
                cat_run.font.bold = True
                cat_run.font.color.rgb = RGBColor(0x00, 0x7A, 0xFF)

            spacer_mid = doc.add_paragraph()
            spacer_mid.paragraph_format.space_before = Pt(160)

            meta_p = doc.add_paragraph()
            meta_run = meta_p.add_run(f"Prepared by: {author}\nDate: {datetime.now().strftime('%B %d, %Y')}")
            meta_run.font.size = Pt(11)
            meta_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

            doc.add_page_break()

        # Document Header (for non-cover pages or main body start)
        if not include_cover_page:
            title_p = doc.add_paragraph()
            title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            title_run = title_p.add_run(title)
            title_run.font.size = Pt(24)
            title_run.font.bold = True
            title_run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
            
            date_p = doc.add_paragraph()
            date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            date_run = date_p.add_run(f"Generated by {author} on {datetime.now().strftime('%B %d, %Y')}")
            date_run.font.size = Pt(10)
            date_run.font.italic = True
            date_run.font.color.rgb = RGBColor(0x7F, 0x7F, 0x7F)
            doc.add_paragraph()

        if isinstance(content, str):
            lines = content.splitlines()
            for line in lines:
                line_str = line.strip()
                if not line_str:
                    continue
                if line_str.startswith("# "):
                    h = doc.add_heading(line_str[2:].strip(), level=1)
                    h.paragraph_format.space_before = Pt(14)
                    h.paragraph_format.space_after = Pt(4)
                elif line_str.startswith("## "):
                    h = doc.add_heading(line_str[3:].strip(), level=2)
                    h.paragraph_format.space_before = Pt(12)
                    h.paragraph_format.space_after = Pt(3)
                elif line_str.startswith("### "):
                    h = doc.add_heading(line_str[4:].strip(), level=3)
                    h.paragraph_format.space_before = Pt(10)
                    h.paragraph_format.space_after = Pt(2)
                elif line_str.startswith("> "):
                    # Callout / quote
                    qp = doc.add_paragraph()
                    qp.paragraph_format.left_indent = Inches(0.5)
                    qp.paragraph_format.right_indent = Inches(0.5)
                    qp.paragraph_format.space_before = Pt(6)
                    qp.paragraph_format.space_after = Pt(6)
                    qrun = qp.add_run(line_str[2:].strip())
                    qrun.font.italic = True
                    qrun.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
                elif line_str.startswith("- ") or line_str.startswith("* ") or line_str.startswith("• "):
                    doc.add_paragraph(line_str[2:].strip(), style='List Bullet')
                elif line_str.startswith("1. ") or line_str.startswith("2. ") or (len(line_str) > 3 and line_str[1:3] == ". "):
                    dot_pos = line_str.find(". ")
                    doc.add_paragraph(line_str[dot_pos+2:].strip(), style='List Number')
                elif line_str == "---" or line_str == "***":
                    doc.add_page_break()
                else:
                    doc.add_paragraph(line_str)
        elif isinstance(content, list):
            for block in content:
                b_type = block.get("type", "paragraph")
                if b_type == "heading":
                    doc.add_heading(block.get("text", ""), level=block.get("level", 1))
                elif b_type == "paragraph":
                    doc.add_paragraph(block.get("text", ""))
                elif b_type in ("quote", "callout"):
                    qp = doc.add_paragraph()
                    qp.paragraph_format.left_indent = Inches(0.5)
                    qp.paragraph_format.right_indent = Inches(0.5)
                    qrun = qp.add_run(f"“{block.get('text', '')}”")
                    qrun.font.italic = True
                    qrun.font.color.rgb = RGBColor(0x22, 0x55, 0x88)
                    if block.get("author"):
                        qp_auth = doc.add_paragraph()
                        qp_auth.paragraph_format.left_indent = Inches(0.5)
                        auth_run = qp_auth.add_run(f"— {block.get('author')}")
                        auth_run.font.bold = True
                        auth_run.font.size = Pt(9.5)
                elif b_type == "bullet":
                    for item in block.get("items", []):
                        doc.add_paragraph(str(item), style='List Bullet')
                elif b_type == "number":
                    for item in block.get("items", []):
                        doc.add_paragraph(str(item), style='List Number')
                elif b_type == "page_break":
                    doc.add_page_break()
                elif b_type == "table":
                    headers = block.get("headers", [])
                    rows = block.get("rows", [])
                    if headers or rows:
                        cols = len(headers) if headers else len(rows[0])
                        table = doc.add_table(rows=0, cols=cols)
                        table.style = 'Light Shading Accent 1'
                        table.alignment = WD_TABLE_ALIGNMENT.CENTER
                        
                        if headers:
                            hdr_cells = table.add_row().cells
                            for i, h_text in enumerate(headers):
                                hdr_cells[i].text = str(h_text)
                                for r in hdr_cells[i].paragraphs[0].runs:
                                    r.font.bold = True
                        
                        for row_data in rows:
                            row_cells = table.add_row().cells
                            for i, cell_val in enumerate(row_data):
                                if i < cols:
                                    row_cells[i].text = str(cell_val)
                        doc.add_paragraph() # Spacing after table

        # Determine output file path
        if not filename:
            safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '_', '-')).rstrip()
            filename = f"{safe_title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
        elif not filename.endswith(".docx"):
            filename += ".docx"

        if os.path.isabs(filename):
            target_path = filename
            out_dir = os.path.dirname(target_path)
        else:
            out_dir = get_default_output_dir()
            target_path = os.path.join(out_dir, filename)

        os.makedirs(os.path.dirname(os.path.abspath(target_path)), exist_ok=True)
        doc.save(target_path)
        logger.info(f"[DOCX] Document saved to: {target_path}")

        return {
            "success": True,
            "status": "success",
            "filepath": target_path,
            "filename": os.path.basename(target_path),
            "message": f"Word document '{os.path.basename(target_path)}' created successfully in {out_dir}."
        }
    except Exception as e:
        logger.error(f"[DOCX] Failed to create document: {e}")
        return {
            "success": False,
            "status": "error",
            "error": str(e),
            "message": f"Failed to create Word document: {e}"
        }
