"""
PDF Document Generator & Utilities for Nova Smart Assistant.
Generates styled PDF files with ReportLab (Page X of Y numbering, running headers)
and provides PDF reading, merging, splitting, and inspection via pypdf.
"""

import os
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def get_default_output_dir() -> str:
    home = os.path.expanduser("~")
    docs = os.path.join(home, "Documents")
    if os.path.exists(docs):
        return docs
    desktop = os.path.join(home, "Desktop")
    if os.path.exists(desktop):
        return desktop
    return home


class _NumberedCanvas:
    """
    Two-pass canvas to dynamically compute total pages and draw 'Page X of Y' footers.
    Instantiated dynamically inside create_pdf_document where ReportLab is imported.
    """
    pass


def _make_numbered_canvas(canvas_cls, doc_title: str, doc_author: str):
    class NumberedCanvas(canvas_cls):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            num_pages = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self.draw_page_decorations(num_pages)
                super().showPage()
            super().save()

        def draw_page_decorations(self, page_count):
            from reportlab.lib import colors
            self.saveState()
            self.setFont("Helvetica", 8.5)
            self.setFillColor(colors.HexColor("#888888"))

            # Header on pages after page 1
            if self._pageNumber > 1:
                self.drawString(54, 750, doc_title[:60])
                self.setStrokeColor(colors.HexColor("#E0E0E0"))
                self.setLineWidth(0.5)
                self.line(54, 745, 558, 745)

            # Footer on all pages
            footer_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(558, 36, footer_text)
            self.drawString(54, 36, f"Generated by {doc_author}")
            self.setStrokeColor(colors.HexColor("#E0E0E0"))
            self.setLineWidth(0.5)
            self.line(54, 48, 558, 48)

            self.restoreState()

    return NumberedCanvas


def create_pdf_document(
    title: str,
    content: str or List[Dict[str, Any]],
    filename: Optional[str] = None,
    author: Optional[str] = "Nova Assistant"
) -> Dict[str, Any]:
    """
    Create a styled PDF document using ReportLab with running headers & Page X of Y footers.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib import colors
        from reportlab.pdfgen import canvas
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        if not filename:
            safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '_', '-')).rstrip()
            filename = f"{safe_title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        elif not filename.endswith(".pdf"):
            filename += ".pdf"

        if os.path.isabs(filename):
            target_path = filename
            out_dir = os.path.dirname(target_path)
        else:
            out_dir = get_default_output_dir()
            target_path = os.path.join(out_dir, filename)

        os.makedirs(os.path.dirname(os.path.abspath(target_path)), exist_ok=True)

        doc = SimpleDocTemplate(
            target_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=60,
            bottomMargin=60
        )

        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1F497D'),
            alignment=TA_CENTER,
            spaceAfter=8
        )
        
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#666666'),
            alignment=TA_CENTER,
            spaceAfter=18
        )
        
        h1_style = ParagraphStyle(
            'CustomH1',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#2E75B6'),
            spaceBefore=14,
            spaceAfter=6
        )

        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor('#262626'),
            spaceAfter=6
        )

        quote_style = ParagraphStyle(
            'CustomQuote',
            parent=body_style,
            fontName='Helvetica-Oblique',
            leftIndent=20,
            rightIndent=20,
            textColor=colors.HexColor('#1F497D'),
            spaceBefore=8,
            spaceAfter=8
        )

        bullet_style = ParagraphStyle(
            'CustomBullet',
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        story = []
        # Title & Subtitle
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"Generated by {author} • {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
        story.append(Spacer(1, 15))

        if isinstance(content, str):
            for line in content.splitlines():
                line_str = line.strip()
                if not line_str:
                    story.append(Spacer(1, 6))
                    continue
                if line_str.startswith("# ") or line_str.startswith("## "):
                    clean_h = line_str.lstrip("#").strip()
                    story.append(Paragraph(clean_h, h1_style))
                elif line_str.startswith("> "):
                    story.append(Paragraph(line_str[2:].strip(), quote_style))
                elif line_str.startswith("- ") or line_str.startswith("* ") or line_str.startswith("• "):
                    clean_b = line_str.lstrip("-*• ").strip()
                    story.append(Paragraph(f"&bull; {clean_b}", bullet_style))
                elif line_str in ("---", "***"):
                    story.append(PageBreak())
                else:
                    story.append(Paragraph(line_str, body_style))
        elif isinstance(content, list):
            for block in content:
                b_type = block.get("type", "paragraph")
                if b_type == "heading":
                    story.append(Paragraph(block.get("text", ""), h1_style))
                elif b_type == "paragraph":
                    story.append(Paragraph(block.get("text", ""), body_style))
                elif b_type in ("quote", "callout"):
                    story.append(Paragraph(f"“{block.get('text', '')}”", quote_style))
                elif b_type == "bullet":
                    for item in block.get("items", []):
                        story.append(Paragraph(f"&bull; {item}", bullet_style))
                elif b_type == "page_break":
                    story.append(PageBreak())
                elif b_type == "table":
                    headers = block.get("headers", [])
                    rows = block.get("rows", [])
                    table_data = []
                    if headers:
                        table_data.append([str(h) for h in headers])
                    for row in rows:
                        table_data.append([str(c) for c in row])
                    if table_data:
                        t = Table(table_data)
                        t.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F497D')),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0, 0), (-1, -1), 9),
                            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F2F5F9')]),
                            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#D9D9D9')),
                        ]))
                        story.append(t)
                        story.append(Spacer(1, 10))

        numbered_canvas_class = _make_numbered_canvas(canvas.Canvas, title, author)
        doc.build(story, canvasmaker=numbered_canvas_class)
        logger.info(f"[PDF] Document saved to: {target_path}")

        return {
            "success": True,
            "status": "success",
            "filepath": target_path,
            "filename": os.path.basename(target_path),
            "message": f"PDF document '{os.path.basename(target_path)}' created successfully in {out_dir}."
        }
    except Exception as e:
        logger.error(f"[PDF] Failed to create document: {e}")
        return {
            "success": False,
            "status": "error",
            "error": str(e),
            "message": f"Failed to create PDF document: {e}"
        }


def extract_pdf_text(filepath: str) -> Dict[str, Any]:
    """
    Extract plain text from an existing PDF file.
    """
    try:
        import pypdf
        if not os.path.exists(filepath):
            return {"success": False, "message": f"File not found: {filepath}"}
            
        reader = pypdf.PdfReader(filepath)
        text_pages = []
        for i, page in enumerate(reader.pages):
            page_text = page.extract_text() or ""
            text_pages.append(f"--- Page {i+1} ---\n{page_text}")
            
        full_text = "\n\n".join(text_pages)
        return {
            "success": True,
            "status": "success",
            "num_pages": len(reader.pages),
            "text": full_text,
            "message": f"Successfully extracted text from {len(reader.pages)} pages."
        }
    except Exception as e:
        return {
            "success": False,
            "status": "error",
            "error": str(e),
            "message": f"Failed to read PDF: {e}"
        }


def get_pdf_info(filepath: str) -> Dict[str, Any]:
    """
    Inspect PDF metadata: page count, title, author, producer, and file size.
    """
    try:
        import pypdf
        if not os.path.exists(filepath):
            return {"success": False, "status": "error", "message": f"PDF file not found: {filepath}"}

        reader = pypdf.PdfReader(filepath)
        meta = reader.metadata or {}
        size_kb = round(os.path.getsize(filepath) / 1024, 1)

        info = {
            "success": True,
            "status": "success",
            "filepath": filepath,
            "filename": os.path.basename(filepath),
            "num_pages": len(reader.pages),
            "size_kb": size_kb,
            "title": meta.get("/Title") or os.path.basename(filepath),
            "author": meta.get("/Author") or "Unknown",
            "creator": meta.get("/Creator") or "Unknown",
            "message": f"PDF '{os.path.basename(filepath)}' has {len(reader.pages)} pages ({size_kb} KB)."
        }
        return info
    except Exception as e:
        return {"success": False, "status": "error", "message": f"Failed to read PDF info: {e}"}


def split_pdf(
    filepath: str,
    start_page: int,
    end_page: int,
    output_filename: Optional[str] = None
) -> Dict[str, Any]:
    """
    Extract a range of pages (1-indexed) into a new PDF document.
    """
    try:
        import pypdf
        if not os.path.exists(filepath):
            return {"success": False, "status": "error", "message": f"File not found: {filepath}"}

        reader = pypdf.PdfReader(filepath)
        total_pages = len(reader.pages)

        # Validate range
        start_idx = max(0, start_page - 1)
        end_idx = min(total_pages, end_page)

        if start_idx >= end_idx or start_idx >= total_pages:
            return {
                "success": False, 
                "status": "error",
                "message": f"Invalid page range {start_page}-{end_page}. Document has {total_pages} pages."
            }

        writer = pypdf.PdfWriter()
        for i in range(start_idx, end_idx):
            writer.add_page(reader.pages[i])

        if not output_filename:
            base_name = os.path.splitext(os.path.basename(filepath))[0]
            output_filename = f"{base_name}_p{start_page}-{end_page}.pdf"
        elif not output_filename.endswith(".pdf"):
            output_filename += ".pdf"

        if os.path.isabs(output_filename):
            target_path = output_filename
            out_dir = os.path.dirname(target_path)
        else:
            out_dir = get_default_output_dir()
            target_path = os.path.join(out_dir, output_filename)

        os.makedirs(os.path.dirname(os.path.abspath(target_path)), exist_ok=True)
        with open(target_path, "wb") as f:
            writer.write(f)

        extracted_count = end_idx - start_idx
        return {
            "success": True,
            "status": "success",
            "filepath": target_path,
            "filename": os.path.basename(target_path),
            "pages_extracted": extracted_count,
            "message": f"Extracted {extracted_count} pages ({start_page}-{end_page}) into '{os.path.basename(target_path)}'."
        }
    except Exception as e:
        return {"success": False, "status": "error", "message": f"Failed to split PDF: {e}"}


def merge_pdfs(file_paths: List[str], output_filename: Optional[str] = None) -> Dict[str, Any]:
    """
    Merge multiple PDF files into a single document.
    """
    try:
        import pypdf
        merger = pypdf.PdfMerger()
        valid_count = 0
        for p in file_paths:
            if os.path.exists(p):
                merger.append(p)
                valid_count += 1
            else:
                logger.warning(f"[PDF] Skipping non-existent path: {p}")
                
        if valid_count < 2:
            return {"success": False, "status": "error", "message": "At least two valid PDF files are required for merging."}

        if not output_filename:
            output_filename = f"Merged_Document_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        elif not output_filename.endswith(".pdf"):
            output_filename += ".pdf"

        if os.path.isabs(output_filename):
            target_path = output_filename
            out_dir = os.path.dirname(target_path)
        else:
            out_dir = get_default_output_dir()
            target_path = os.path.join(out_dir, output_filename)

        os.makedirs(os.path.dirname(os.path.abspath(target_path)), exist_ok=True)
        merger.write(target_path)
        merger.close()

        return {
            "success": True,
            "status": "success",
            "filepath": target_path,
            "filename": os.path.basename(target_path),
            "merged_count": valid_count,
            "message": f"Merged {valid_count} PDF files into '{os.path.basename(target_path)}'."
        }
    except Exception as e:
        return {
            "success": False,
            "status": "error",
            "error": str(e),
            "message": f"Failed to merge PDFs: {e}"
        }
