"""
PowerPoint (.pptx) Presentation Generator for Nova Smart Assistant.
Generates styled presentations with title slides, bullet layouts, section dividers,
tables, and speaker notes using python-pptx.
"""

import os
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def get_default_output_dir() -> str:
    home = os.path.expanduser("~")
    docs = os.path.join(home, "Documents")
    if os.path.exists(docs):
        return docs
    desktop = os.path.join(home, "Desktop")
    if os.path.exists(desktop):
        return desktop
    return home


# Color palette themes for slides
THEMES = {
    "navy": {
        "primary": (31, 73, 125),       # Deep Navy
        "accent": (46, 117, 182),       # Ocean Blue
        "background": (255, 255, 255),
        "text": (38, 38, 38),
        "header_text": (31, 73, 125)
    },
    "slate": {
        "primary": (47, 79, 79),        # Dark Slate Gray
        "accent": (0, 128, 128),        # Teal
        "background": (255, 255, 255),
        "text": (40, 40, 40),
        "header_text": (47, 79, 79)
    }
}


def create_presentation(
    title: str,
    subtitle: Optional[str] = None,
    slides: Optional[List[Dict[str, Any]]] = None,
    filename: Optional[str] = None,
    author: Optional[str] = "Nova Assistant",
    theme: str = "navy"
) -> Dict[str, Any]:
    """
    Create a styled PowerPoint presentation (.pptx).
    
    Args:
        title: Presentation title (Slide 1)
        subtitle: Subtitle or presentation metadata
        slides: List of slide specifications:
                [
                  {"type": "content", "title": "...", "bullets": ["...", "..."], "notes": "..."},
                  {"type": "section", "title": "...", "subtitle": "..."},
                  {"type": "table", "title": "...", "headers": [...], "rows": [[...], ...]}
                ]
        filename: Optional output filename (.pptx)
        author: Document author metadata
        theme: "navy" or "slate"
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN

        prs = Presentation()
        prs.slide_width = Inches(13.333) # 16:9 widescreen
        prs.slide_height = Inches(7.5)

        pal = THEMES.get(theme.lower(), THEMES["navy"])
        c_primary = RGBColor(*pal["primary"])
        c_accent = RGBColor(*pal["accent"])
        c_text = RGBColor(*pal["text"])

        # Slide 1: Title Slide (Blank slide layout with custom shapes)
        blank_layout = prs.slide_layouts[6]
        title_slide = prs.slides.add_slide(blank_layout)

        # Title Box
        t_box = title_slide.shapes.add_textbox(Inches(1.5), Inches(2.2), Inches(10.3), Inches(2.2))
        tf = t_box.text_frame
        tf.word_wrap = True
        p_title = tf.paragraphs[0]
        p_title.text = title
        p_title.font.name = "Calibri"
        p_title.font.size = Pt(44)
        p_title.font.bold = True
        p_title.font.color.rgb = c_primary

        # Subtitle
        sub_text = subtitle or f"Generated by {author} • {datetime.now().strftime('%B %d, %Y')}"
        p_sub = tf.add_paragraph()
        p_sub.text = sub_text
        p_sub.font.name = "Calibri"
        p_sub.font.size = Pt(18)
        p_sub.font.color.rgb = c_accent
        p_sub.space_before = Pt(14)

        # Speaker notes for title slide
        notes_slide = title_slide.notes_slide
        notes_slide.notes_text_frame.text = f"Presentation: {title}. Prepared by {author} on {datetime.now().strftime('%Y-%m-%d')}."

        # Add Subsequent Slides
        if slides:
            for s_info in slides:
                s_type = s_info.get("type", "content")
                s_title = s_info.get("title", "")
                s_notes = s_info.get("notes")

                slide = prs.slides.add_slide(blank_layout)

                if s_type == "section":
                    # Section Divider Slide
                    box = slide.shapes.add_textbox(Inches(1.5), Inches(2.8), Inches(10.3), Inches(2.0))
                    tf_sec = box.text_frame
                    tf_sec.word_wrap = True
                    p_sec = tf_sec.paragraphs[0]
                    p_sec.text = s_title
                    p_sec.font.name = "Calibri"
                    p_sec.font.size = Pt(38)
                    p_sec.font.bold = True
                    p_sec.font.color.rgb = c_primary

                    if s_info.get("subtitle"):
                        p_sec_sub = tf_sec.add_paragraph()
                        p_sec_sub.text = s_info.get("subtitle")
                        p_sec_sub.font.name = "Calibri"
                        p_sec_sub.font.size = Pt(16)
                        p_sec_sub.font.color.rgb = c_accent
                        p_sec_sub.space_before = Pt(10)

                elif s_type == "table":
                    # Table Slide
                    # Slide Header
                    h_box = slide.shapes.add_textbox(Inches(1.0), Inches(0.6), Inches(11.3), Inches(1.0))
                    h_tf = h_box.text_frame
                    p_head = h_tf.paragraphs[0]
                    p_head.text = s_title
                    p_head.font.name = "Calibri"
                    p_head.font.size = Pt(28)
                    p_head.font.bold = True
                    p_head.font.color.rgb = c_primary

                    headers = s_info.get("headers", [])
                    rows = s_info.get("rows", [])
                    num_rows = len(rows) + (1 if headers else 0)
                    num_cols = len(headers) if headers else (len(rows[0]) if rows else 1)

                    if num_rows > 0 and num_cols > 0:
                        table_shape = slide.shapes.add_table(num_rows, num_cols, Inches(1.0), Inches(1.8), Inches(11.3), Inches(4.5))
                        tbl = table_shape.table

                        r_offset = 0
                        if headers:
                            for c_idx, h in enumerate(headers):
                                cell = tbl.cell(0, c_idx)
                                cell.text = str(h)
                                for p in cell.text_frame.paragraphs:
                                    p.font.name = "Calibri"
                                    p.font.bold = True
                                    p.font.size = Pt(12)
                                    p.font.color.rgb = RGBColor(255, 255, 255)
                                    p.alignment = PP_ALIGN.CENTER
                                cell.fill.solid()
                                cell.fill.fore_color.rgb = c_primary
                            r_offset = 1

                        for r_idx, r_data in enumerate(rows):
                            for c_idx, val in enumerate(r_data[:num_cols]):
                                cell = tbl.cell(r_idx + r_offset, c_idx)
                                cell.text = str(val)
                                for p in cell.text_frame.paragraphs:
                                    p.font.name = "Calibri"
                                    p.font.size = Pt(11)
                                    p.font.color.rgb = c_text

                else:
                    # Content / Bullet Slide
                    h_box = slide.shapes.add_textbox(Inches(1.0), Inches(0.6), Inches(11.3), Inches(1.0))
                    h_tf = h_box.text_frame
                    p_head = h_tf.paragraphs[0]
                    p_head.text = s_title
                    p_head.font.name = "Calibri"
                    p_head.font.size = Pt(28)
                    p_head.font.bold = True
                    p_head.font.color.rgb = c_primary

                    body_box = slide.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.3), Inches(5.0))
                    body_tf = body_box.text_frame
                    body_tf.word_wrap = True

                    bullets = s_info.get("bullets", [])
                    for b_idx, bullet_text in enumerate(bullets):
                        p_bullet = body_tf.paragraphs[0] if b_idx == 0 else body_tf.add_paragraph()
                        p_bullet.text = str(bullet_text)
                        p_bullet.font.name = "Calibri"
                        p_bullet.font.size = Pt(16)
                        p_bullet.font.color.rgb = c_text
                        p_bullet.space_before = Pt(10)
                        p_bullet.level = 0

                # Speaker notes
                if s_notes:
                    s_notes_slide = slide.notes_slide
                    s_notes_slide.notes_text_frame.text = str(s_notes)

        # Output filename
        if not filename:
            safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '_', '-')).rstrip()
            filename = f"{safe_title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        elif not filename.endswith(".pptx"):
            filename += ".pptx"

        if os.path.isabs(filename):
            target_path = filename
            out_dir = os.path.dirname(target_path)
        else:
            out_dir = get_default_output_dir()
            target_path = os.path.join(out_dir, filename)

        os.makedirs(os.path.dirname(os.path.abspath(target_path)), exist_ok=True)
        prs.save(target_path)
        logger.info(f"[PPTX] Presentation saved to: {target_path}")

        total_slides = 1 + (len(slides) if slides else 0)
        return {
            "success": True,
            "status": "success",
            "filepath": target_path,
            "filename": os.path.basename(target_path),
            "slide_count": total_slides,
            "message": f"PowerPoint presentation '{os.path.basename(target_path)}' with {total_slides} slides created in {out_dir}."
        }
    except Exception as e:
        logger.error(f"[PPTX] Failed to create presentation: {e}")
        return {
            "success": False,
            "status": "error",
            "error": str(e),
            "message": f"Failed to create PowerPoint presentation: {e}"
        }
